[package]
name = "server_socket"
version = "0.1.0"
authors = ["Kirill Kamakin <k.kamakin@protonmail.ch>"]

[dependencies]
libc = "0.2"
dirs = "1.0"
simple-signal = "1.1"
bincode = "1.0"
serde = "1.0"
serde_derive = "1.0"